*** Starting uWSGI 2.0.21 (64bit) on [Wed May 24 08:29:48 2023] ***
compiled with version: 11.2.0 on 23 May 2023 23:59:10
os: Linux-5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022
nodename: VM-16-9-ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /home/ubuntu/files/se1/soul-qn-django/soul_qn_django
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/ubuntu/files/se1/soul-qn-django/soul_qn_django/manage.py
chdir(): Not a directory [core/uwsgi.c line 2625]
*** Starting uWSGI 2.0.21 (64bit) on [Wed May 24 08:30:45 2023] ***
compiled with version: 11.2.0 on 23 May 2023 23:59:10
os: Linux-5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022
nodename: VM-16-9-ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /home/ubuntu/files/se1/soul-qn-django/soul_qn_django
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/ubuntu/files/se1/soul-qn-django/soul_qn_django/manage.py
chdir(): Not a directory [core/uwsgi.c line 2625]
*** Starting uWSGI 2.0.21 (64bit) on [Wed May 24 09:26:33 2023] ***
compiled with version: 11.2.0 on 23 May 2023 23:59:10
os: Linux-5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022
nodename: VM-16-9-ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /home/ubuntu/files/se1/soul-qn-django/soul_qn_django
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/ubuntu/files/se1/soul-qn-django/soul_qn_django
your processes number limit is 7458
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:5000 fd 3
Python version: 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0]
Python main interpreter initialized at 0x558fba73d1c0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1031270 bytes (1007 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
Traceback (most recent call last):
  File "soul_qn_django/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 149109)
spawned uWSGI worker 1 (pid: 149110, cores: 2)
spawned uWSGI worker 2 (pid: 149111, cores: 2)
spawned uWSGI worker 3 (pid: 149113, cores: 2)
spawned uWSGI worker 4 (pid: 149114, cores: 2)
--- no python application found, check your startup logs for errors ---
[pid: 149111|app: -1|req: -1/1] 219.239.227.110 () {40 vars in 574 bytes} [Wed May 24 09:27:17 2023] POST /api/user_about/login => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 149111|app: -1|req: -1/2] 219.239.227.110 () {40 vars in 574 bytes} [Wed May 24 09:27:41 2023] POST /api/user_about/login => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 149111|app: -1|req: -1/3] 219.239.227.110 () {40 vars in 574 bytes} [Wed May 24 09:30:21 2023] POST /api/user_about/login => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.21 (64bit) on [Wed May 24 09:42:45 2023] ***
compiled with version: 11.2.0 on 23 May 2023 23:59:10
os: Linux-5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022
nodename: VM-16-9-ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /home/ubuntu/files/se1/soul-qn-django/soul_qn_django
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/ubuntu/files/se1/soul-qn-django/soul_qn_django
your processes number limit is 7458
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:5000).
bind(): Address already in use [core/socket.c line 769]
--- no python application found, check your startup logs for errors ---
[pid: 149111|app: -1|req: -1/4] 219.239.227.110 () {40 vars in 574 bytes} [Wed May 24 09:42:56 2023] POST /api/user_about/login => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
*** Starting uWSGI 2.0.21 (64bit) on [Wed May 24 09:45:41 2023] ***
compiled with version: 11.2.0 on 23 May 2023 23:59:10
os: Linux-5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022
nodename: VM-16-9-ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /home/ubuntu/files/se1/soul-qn-django/soul_qn_django
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/ubuntu/files/se1/soul-qn-django/soul_qn_django
your processes number limit is 7458
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:5000 fd 3
Python version: 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0]
Set PythonHome to /home/ubuntu/miniconda3/envs/django_env
Python main interpreter initialized at 0x556943350730
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1031270 bytes (1007 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x556943350730 pid: 153842 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 153842)
spawned uWSGI worker 1 (pid: 153845, cores: 2)
spawned uWSGI worker 2 (pid: 153847, cores: 2)
spawned uWSGI worker 3 (pid: 153848, cores: 2)
spawned uWSGI worker 4 (pid: 153850, cores: 2)
Invalid HTTP_HOST header: '82.156.154.154'. You may need to add '82.156.154.154' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/django_env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/django_env/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/miniconda3/envs/django_env/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/miniconda3/envs/django_env/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '82.156.154.154'. You may need to add '82.156.154.154' to ALLOWED_HOSTS.
Bad Request: /api/user_about/login
[pid: 153848|app: 0|req: 1/1] 219.239.227.110 () {40 vars in 574 bytes} [Wed May 24 09:45:45 2023] POST /api/user_about/login => generated 58627 bytes in 237 msecs (HTTP/1.1 400) 5 headers in 186 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '82.156.154.154'. You may need to add '82.156.154.154' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/django_env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/django_env/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/miniconda3/envs/django_env/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/miniconda3/envs/django_env/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '82.156.154.154'. You may need to add '82.156.154.154' to ALLOWED_HOSTS.
Bad Request: /api/user_about/login
[pid: 153850|app: 0|req: 1/2] 219.239.227.110 () {40 vars in 574 bytes} [Wed May 24 09:47:47 2023] POST /api/user_about/login => generated 58627 bytes in 240 msecs (HTTP/1.1 400) 5 headers in 186 bytes (1 switches on core 0)
...gracefully killing workers...
Gracefully killing worker 3 (pid: 153848)...
Gracefully killing worker 1 (pid: 153845)...
Gracefully killing worker 2 (pid: 153847)...
Gracefully killing worker 4 (pid: 153850)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/ubuntu/files/se1/soul-qn-django/soul_qn_django
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:5000)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.21 (64bit) on [Wed May 24 09:48:03 2023] ***
compiled with version: 11.2.0 on 23 May 2023 23:59:10
os: Linux-5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022
nodename: VM-16-9-ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /home/ubuntu/files/se1/soul-qn-django/soul_qn_django
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/ubuntu/files/se1/soul-qn-django/soul_qn_django
your processes number limit is 7458
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:5000 fd 3
Python version: 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0]
Set PythonHome to /home/ubuntu/miniconda3/envs/django_env
Python main interpreter initialized at 0x55ef81afe120
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1031270 bytes (1007 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55ef81afe120 pid: 153842 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 153842)
spawned uWSGI worker 1 (pid: 154446, cores: 2)
spawned uWSGI worker 2 (pid: 154448, cores: 2)
spawned uWSGI worker 3 (pid: 154449, cores: 2)
spawned uWSGI worker 4 (pid: 154451, cores: 2)
*** Starting uWSGI 2.0.21 (64bit) on [Wed May 24 09:48:05 2023] ***
compiled with version: 11.2.0 on 23 May 2023 23:59:10
os: Linux-5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022
nodename: VM-16-9-ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /home/ubuntu/files/se1/soul-qn-django/soul_qn_django
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/ubuntu/files/se1/soul-qn-django/soul_qn_django
your processes number limit is 7458
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:5000).
bind(): Address already in use [core/socket.c line 769]
[pid: 154451|app: 0|req: 1/1] 219.239.227.110 () {40 vars in 574 bytes} [Wed May 24 09:48:09 2023] POST /api/user_about/login => generated 265 bytes in 384 msecs (HTTP/1.1 200) 7 headers in 213 bytes (1 switches on core 0)
